services:
  - type: web
    plan: free
    name: demo-app
    runtime: ruby
    repo: https://github.com/codemodeb/demo.git
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec rails server'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: demo
          property: connectionString

databases:
  - name: demo
    plan: free
